name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  glob:  # id of input
    description: 'Files to be included in calculation, separate multiple globs by a single space'
    required: true
    default: '**'
outputs:
  checksums: # id of output
    description: 'Formatted text containing checksums'
runs:
  using: 'node12'
  main: 'index.js'
